---
abstract: 'Log to files that archive/rotate themselves, w/ File::Write::Rotate'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-FileWriteRotate
requires:
  File::Write::Rotate: 0
  Log::Dispatch::Output: 0
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Log-Dispatch-FileWriteRotate
  homepage: https://metacpan.org/release/Log-Dispatch-FileWriteRotate
  repository: git://github.com/sharyanto/perl-Log-Dispatch-FileWriteRotate.git
version: 0.02
